import { buildMonthlySnapshot } from "@/lib/monthly-snapshots";
import {
  appSettingsSchema,
  budgetCategorySchema,
  budgetPlanSchema,
  merchantRuleSchema,
  monthlySnapshotSchema,
  statementImportSchema,
  transactionSchema,
  type AppSettings,
  type BudgetCategory,
  type BudgetPlan,
  type MerchantRule,
  type MonthlySnapshot,
  type StatementImport,
  type Transaction,
} from "@/types";

const seededAt = "2026-03-15T12:00:00.000Z";
const settingsId = "app-settings" as const;
const planId = "budget-plan-baseline";

const categoryIds = {
  amazon: "category-shopping",
  dining: "category-dining",
  freelance: "category-freelance",
  groceries: "category-groceries",
  insurance: "category-insurance",
  rent: "category-rent",
  salary: "category-salary",
  subscriptions: "category-subscriptions",
  transport: "category-transport",
  utilities: "category-utilities",
} as const;

const importIds = {
  february: "statement-import-2026-02",
  january: "statement-import-2026-01",
  march: "statement-import-2026-03",
} as const;

function createCategory(input: BudgetCategory) {
  return budgetCategorySchema.parse(input);
}

function createPlan(input: BudgetPlan) {
  return budgetPlanSchema.parse(input);
}

function createRule(input: MerchantRule) {
  return merchantRuleSchema.parse(input);
}

function createImport(input: StatementImport) {
  return statementImportSchema.parse(input);
}

function createTransaction(input: Transaction) {
  return transactionSchema.parse(input);
}

function createSettings(input: AppSettings) {
  return appSettingsSchema.parse(input);
}

const budgetCategories = [
  createCategory({
    archived: false,
    color: "#356f64",
    iconKey: "briefcase",
    id: categoryIds.salary,
    kind: "income",
    mode: "fixed",
    name: "Salary",
    plannedAmount: 520_000,
    sortOrder: 10,
  }),
  createCategory({
    archived: false,
    color: "#5b907b",
    iconKey: "sparkles",
    id: categoryIds.freelance,
    kind: "income",
    mode: "variable",
    name: "Freelance",
    plannedAmount: 30_000,
    sortOrder: 20,
  }),
  createCategory({
    archived: false,
    color: "#b36f4a",
    iconKey: "home",
    id: categoryIds.rent,
    kind: "expense",
    mode: "fixed",
    name: "Rent",
    plannedAmount: 165_000,
    sortOrder: 30,
  }),
  createCategory({
    archived: false,
    color: "#d38d42",
    iconKey: "zap",
    id: categoryIds.utilities,
    kind: "expense",
    mode: "fixed",
    name: "Utilities",
    plannedAmount: 21_000,
    sortOrder: 40,
  }),
  createCategory({
    archived: false,
    color: "#8f5a6b",
    iconKey: "shield",
    id: categoryIds.insurance,
    kind: "expense",
    mode: "fixed",
    name: "Insurance",
    plannedAmount: 17_500,
    sortOrder: 50,
  }),
  createCategory({
    archived: false,
    color: "#5d5f9e",
    iconKey: "film",
    id: categoryIds.subscriptions,
    kind: "expense",
    mode: "fixed",
    name: "Subscriptions",
    plannedAmount: 2_400,
    sortOrder: 60,
  }),
  createCategory({
    archived: false,
    color: "#597a4b",
    iconKey: "shopping-basket",
    id: categoryIds.groceries,
    kind: "expense",
    mode: "variable",
    name: "Groceries",
    plannedAmount: 65_000,
    sortOrder: 70,
  }),
  createCategory({
    archived: false,
    color: "#7a4f43",
    iconKey: "utensils",
    id: categoryIds.dining,
    kind: "expense",
    mode: "variable",
    name: "Dining",
    plannedAmount: 22_000,
    sortOrder: 80,
  }),
  createCategory({
    archived: false,
    color: "#4b6f93",
    iconKey: "car",
    id: categoryIds.transport,
    kind: "expense",
    mode: "variable",
    name: "Transport",
    plannedAmount: 18_000,
    sortOrder: 90,
  }),
  createCategory({
    archived: false,
    color: "#6f6751",
    iconKey: "package",
    id: categoryIds.amazon,
    kind: "expense",
    mode: "variable",
    name: "Shopping",
    plannedAmount: 12_000,
    sortOrder: 100,
  }),
];

const budgetPlan = createPlan({
  archived: false,
  categoryIds: budgetCategories.map((category) => category.id),
  createdAt: seededAt,
  currency: "USD",
  expectedSavings: 227_100,
  id: planId,
  isDefault: true,
  monthStartDay: 1,
  name: "Baseline household budget",
  notes:
    "Demo baseline that mixes fixed monthly obligations with variable spending categories.",
  updatedAt: seededAt,
});

const statementImports = [
  createImport({
    checksum: "seed-2026-01-statement",
    columnMap: {
      amount: "Amount",
      date: "Date",
      merchant: "Merchant",
    },
    duplicateRowCount: 0,
    fileName: "2026-01-credit-card.xlsx",
    id: importIds.january,
    importedAt: seededAt,
    importedRowCount: 8,
    monthKey: "2026-01",
    sourceFormat: "seed",
    status: "committed",
    totalRowCount: 8,
    warningCount: 0,
    warnings: [],
  }),
  createImport({
    checksum: "seed-2026-02-statement",
    columnMap: {
      amount: "Amount",
      date: "Date",
      merchant: "Merchant",
    },
    duplicateRowCount: 0,
    fileName: "2026-02-credit-card.csv",
    id: importIds.february,
    importedAt: seededAt,
    importedRowCount: 8,
    monthKey: "2026-02",
    sourceFormat: "seed",
    status: "committed",
    totalRowCount: 8,
    warningCount: 0,
    warnings: [],
  }),
  createImport({
    checksum: "seed-2026-03-statement",
    columnMap: {
      amount: "Amount",
      date: "Date",
      merchant: "Merchant",
    },
    duplicateRowCount: 0,
    fileName: "2026-03-credit-card.xlsx",
    id: importIds.march,
    importedAt: seededAt,
    importedRowCount: 9,
    monthKey: "2026-03",
    sourceFormat: "seed",
    status: "committed",
    totalRowCount: 9,
    warningCount: 0,
    warnings: [],
  }),
];

const transactions = [
  createTransaction({
    amount: 520_000,
    categoryId: categoryIds.salary,
    createdAt: seededAt,
    date: "2026-01-01",
    direction: "income",
    id: "transaction-2026-01-salary",
    ignored: false,
    merchantNormalized: "ACME PAYROLL",
    merchantRaw: "Acme Payroll",
    monthKey: "2026-01",
    notes: "Primary paycheck",
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 24_000,
    categoryId: categoryIds.freelance,
    createdAt: seededAt,
    date: "2026-01-18",
    direction: "income",
    id: "transaction-2026-01-freelance",
    ignored: false,
    merchantNormalized: "CLIENT PAYOUT",
    merchantRaw: "Client payout",
    monthKey: "2026-01",
    notes: "Design retainer",
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 165_000,
    categoryId: categoryIds.rent,
    createdAt: seededAt,
    date: "2026-01-02",
    direction: "expense",
    id: "transaction-2026-01-rent",
    ignored: false,
    merchantNormalized: "RIVERSIDE PROPERTY",
    merchantRaw: "Riverside Property",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 21_250,
    categoryId: categoryIds.utilities,
    createdAt: seededAt,
    date: "2026-01-06",
    direction: "expense",
    id: "transaction-2026-01-utilities",
    ignored: false,
    merchantNormalized: "CITY UTILITIES",
    merchantRaw: "City Utilities",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 17_500,
    categoryId: categoryIds.insurance,
    createdAt: seededAt,
    date: "2026-01-10",
    direction: "expense",
    id: "transaction-2026-01-insurance",
    ignored: false,
    merchantNormalized: "NOVA INSURANCE",
    merchantRaw: "Nova Insurance",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 14_860,
    categoryId: categoryIds.groceries,
    createdAt: seededAt,
    date: "2026-01-04",
    direction: "expense",
    id: "transaction-2026-01-whole-foods",
    ignored: false,
    merchantNormalized: "WHOLE FOODS",
    merchantRaw: "Whole Foods Market",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: importIds.january,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 9_125,
    categoryId: categoryIds.groceries,
    createdAt: seededAt,
    date: "2026-01-11",
    direction: "expense",
    id: "transaction-2026-01-trader-joes",
    ignored: false,
    merchantNormalized: "TRADER JOES",
    merchantRaw: "Trader Joe's",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: importIds.january,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 1_840,
    categoryId: categoryIds.dining,
    createdAt: seededAt,
    date: "2026-01-13",
    direction: "expense",
    id: "transaction-2026-01-sweetgreen",
    ignored: false,
    merchantNormalized: "SWEETGREEN",
    merchantRaw: "Sweetgreen",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: importIds.january,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 675,
    categoryId: categoryIds.dining,
    createdAt: seededAt,
    date: "2026-01-17",
    direction: "expense",
    id: "transaction-2026-01-blue-bottle",
    ignored: false,
    merchantNormalized: "BLUE BOTTLE",
    merchantRaw: "Blue Bottle Coffee",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: importIds.january,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 2_240,
    categoryId: categoryIds.transport,
    createdAt: seededAt,
    date: "2026-01-20",
    direction: "expense",
    id: "transaction-2026-01-uber",
    ignored: false,
    merchantNormalized: "UBER",
    merchantRaw: "Uber Trip",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: importIds.january,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 5_980,
    categoryId: categoryIds.transport,
    createdAt: seededAt,
    date: "2026-01-23",
    direction: "expense",
    id: "transaction-2026-01-shell",
    ignored: false,
    merchantNormalized: "SHELL",
    merchantRaw: "Shell Service Station",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: importIds.january,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 4_625,
    categoryId: categoryIds.amazon,
    createdAt: seededAt,
    date: "2026-01-24",
    direction: "expense",
    id: "transaction-2026-01-amazon",
    ignored: false,
    merchantNormalized: "AMAZON",
    merchantRaw: "Amazon Marketplace",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: importIds.january,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 1_600,
    categoryId: categoryIds.subscriptions,
    createdAt: seededAt,
    date: "2026-01-27",
    direction: "expense",
    id: "transaction-2026-01-netflix",
    ignored: false,
    merchantNormalized: "NETFLIX",
    merchantRaw: "Netflix",
    monthKey: "2026-01",
    notes: null,
    sourceImportId: importIds.january,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 520_000,
    categoryId: categoryIds.salary,
    createdAt: seededAt,
    date: "2026-02-01",
    direction: "income",
    id: "transaction-2026-02-salary",
    ignored: false,
    merchantNormalized: "ACME PAYROLL",
    merchantRaw: "Acme Payroll",
    monthKey: "2026-02",
    notes: "Primary paycheck",
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 31_000,
    categoryId: categoryIds.freelance,
    createdAt: seededAt,
    date: "2026-02-19",
    direction: "income",
    id: "transaction-2026-02-freelance",
    ignored: false,
    merchantNormalized: "CLIENT PAYOUT",
    merchantRaw: "Client payout",
    monthKey: "2026-02",
    notes: "Template refresh project",
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 165_000,
    categoryId: categoryIds.rent,
    createdAt: seededAt,
    date: "2026-02-02",
    direction: "expense",
    id: "transaction-2026-02-rent",
    ignored: false,
    merchantNormalized: "RIVERSIDE PROPERTY",
    merchantRaw: "Riverside Property",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 19_840,
    categoryId: categoryIds.utilities,
    createdAt: seededAt,
    date: "2026-02-05",
    direction: "expense",
    id: "transaction-2026-02-utilities",
    ignored: false,
    merchantNormalized: "CITY UTILITIES",
    merchantRaw: "City Utilities",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 17_500,
    categoryId: categoryIds.insurance,
    createdAt: seededAt,
    date: "2026-02-10",
    direction: "expense",
    id: "transaction-2026-02-insurance",
    ignored: false,
    merchantNormalized: "NOVA INSURANCE",
    merchantRaw: "Nova Insurance",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 16_320,
    categoryId: categoryIds.groceries,
    createdAt: seededAt,
    date: "2026-02-04",
    direction: "expense",
    id: "transaction-2026-02-whole-foods",
    ignored: false,
    merchantNormalized: "WHOLE FOODS",
    merchantRaw: "Whole Foods Market",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: importIds.february,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 10_410,
    categoryId: categoryIds.groceries,
    createdAt: seededAt,
    date: "2026-02-12",
    direction: "expense",
    id: "transaction-2026-02-trader-joes",
    ignored: false,
    merchantNormalized: "TRADER JOES",
    merchantRaw: "Trader Joe's",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: importIds.february,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 1_950,
    categoryId: categoryIds.dining,
    createdAt: seededAt,
    date: "2026-02-13",
    direction: "expense",
    id: "transaction-2026-02-chipotle",
    ignored: false,
    merchantNormalized: "CHIPOTLE",
    merchantRaw: "Chipotle",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: importIds.february,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 4_620,
    categoryId: categoryIds.dining,
    createdAt: seededAt,
    date: "2026-02-15",
    direction: "expense",
    id: "transaction-2026-02-local-bistro",
    ignored: false,
    merchantNormalized: "LOCAL BISTRO",
    merchantRaw: "Local Bistro",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: importIds.february,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 1_380,
    categoryId: categoryIds.transport,
    createdAt: seededAt,
    date: "2026-02-16",
    direction: "expense",
    id: "transaction-2026-02-metro",
    ignored: false,
    merchantNormalized: "METRO CARD",
    merchantRaw: "Metro Card Reload",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: importIds.february,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 2_840,
    categoryId: categoryIds.transport,
    createdAt: seededAt,
    date: "2026-02-18",
    direction: "expense",
    id: "transaction-2026-02-uber",
    ignored: false,
    merchantNormalized: "UBER",
    merchantRaw: "Uber Trip",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: importIds.february,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 5_890,
    categoryId: categoryIds.amazon,
    createdAt: seededAt,
    date: "2026-02-22",
    direction: "expense",
    id: "transaction-2026-02-amazon",
    ignored: false,
    merchantNormalized: "AMAZON",
    merchantRaw: "Amazon Marketplace",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: importIds.february,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 1_600,
    categoryId: categoryIds.subscriptions,
    createdAt: seededAt,
    date: "2026-02-27",
    direction: "expense",
    id: "transaction-2026-02-netflix",
    ignored: false,
    merchantNormalized: "NETFLIX",
    merchantRaw: "Netflix",
    monthKey: "2026-02",
    notes: null,
    sourceImportId: importIds.february,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 520_000,
    categoryId: categoryIds.salary,
    createdAt: seededAt,
    date: "2026-03-01",
    direction: "income",
    id: "transaction-2026-03-salary",
    ignored: false,
    merchantNormalized: "ACME PAYROLL",
    merchantRaw: "Acme Payroll",
    monthKey: "2026-03",
    notes: "Primary paycheck",
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 28_000,
    categoryId: categoryIds.freelance,
    createdAt: seededAt,
    date: "2026-03-21",
    direction: "income",
    id: "transaction-2026-03-freelance",
    ignored: false,
    merchantNormalized: "CLIENT PAYOUT",
    merchantRaw: "Client payout",
    monthKey: "2026-03",
    notes: "Landing page polish work",
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 165_000,
    categoryId: categoryIds.rent,
    createdAt: seededAt,
    date: "2026-03-02",
    direction: "expense",
    id: "transaction-2026-03-rent",
    ignored: false,
    merchantNormalized: "RIVERSIDE PROPERTY",
    merchantRaw: "Riverside Property",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 22_710,
    categoryId: categoryIds.utilities,
    createdAt: seededAt,
    date: "2026-03-05",
    direction: "expense",
    id: "transaction-2026-03-utilities",
    ignored: false,
    merchantNormalized: "CITY UTILITIES",
    merchantRaw: "City Utilities",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 17_500,
    categoryId: categoryIds.insurance,
    createdAt: seededAt,
    date: "2026-03-10",
    direction: "expense",
    id: "transaction-2026-03-insurance",
    ignored: false,
    merchantNormalized: "NOVA INSURANCE",
    merchantRaw: "Nova Insurance",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: null,
    sourceType: "manual",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 17_140,
    categoryId: categoryIds.groceries,
    createdAt: seededAt,
    date: "2026-03-04",
    direction: "expense",
    id: "transaction-2026-03-whole-foods",
    ignored: false,
    merchantNormalized: "WHOLE FOODS",
    merchantRaw: "Whole Foods Market",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: importIds.march,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 8_935,
    categoryId: categoryIds.groceries,
    createdAt: seededAt,
    date: "2026-03-13",
    direction: "expense",
    id: "transaction-2026-03-farm-boy",
    ignored: false,
    merchantNormalized: "FARM BOY",
    merchantRaw: "Farm Boy",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: importIds.march,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 2_140,
    categoryId: categoryIds.dining,
    createdAt: seededAt,
    date: "2026-03-14",
    direction: "expense",
    id: "transaction-2026-03-sweetgreen",
    ignored: false,
    merchantNormalized: "SWEETGREEN",
    merchantRaw: "Sweetgreen",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: importIds.march,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 2_875,
    categoryId: categoryIds.dining,
    createdAt: seededAt,
    date: "2026-03-15",
    direction: "expense",
    id: "transaction-2026-03-pizza",
    ignored: false,
    merchantNormalized: "PIZZA NORTH",
    merchantRaw: "Pizza North",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: importIds.march,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 3_190,
    categoryId: categoryIds.transport,
    createdAt: seededAt,
    date: "2026-03-16",
    direction: "expense",
    id: "transaction-2026-03-uber",
    ignored: false,
    merchantNormalized: "UBER",
    merchantRaw: "Uber Trip",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: importIds.march,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 6_420,
    categoryId: categoryIds.transport,
    createdAt: seededAt,
    date: "2026-03-22",
    direction: "expense",
    id: "transaction-2026-03-shell",
    ignored: false,
    merchantNormalized: "SHELL",
    merchantRaw: "Shell Service Station",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: importIds.march,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 7_280,
    categoryId: categoryIds.amazon,
    createdAt: seededAt,
    date: "2026-03-23",
    direction: "expense",
    id: "transaction-2026-03-amazon",
    ignored: false,
    merchantNormalized: "AMAZON",
    merchantRaw: "Amazon Marketplace",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: importIds.march,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 1_600,
    categoryId: categoryIds.subscriptions,
    createdAt: seededAt,
    date: "2026-03-26",
    direction: "expense",
    id: "transaction-2026-03-netflix",
    ignored: false,
    merchantNormalized: "NETFLIX",
    merchantRaw: "Netflix",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: importIds.march,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
  createTransaction({
    amount: 1_099,
    categoryId: categoryIds.subscriptions,
    createdAt: seededAt,
    date: "2026-03-28",
    direction: "expense",
    id: "transaction-2026-03-apple",
    ignored: false,
    merchantNormalized: "APPLE SERVICES",
    merchantRaw: "Apple Services",
    monthKey: "2026-03",
    notes: null,
    sourceImportId: importIds.march,
    sourceType: "statement_import",
    transferLike: false,
    updatedAt: seededAt,
  }),
];

const merchantRules = [
  createRule({
    categoryId: categoryIds.groceries,
    createdAt: seededAt,
    id: "rule-whole-foods",
    isCaseSensitive: false,
    matchType: "contains",
    pattern: "WHOLE FOODS",
    priority: 100,
    updatedAt: seededAt,
  }),
  createRule({
    categoryId: categoryIds.groceries,
    createdAt: seededAt,
    id: "rule-trader-joes",
    isCaseSensitive: false,
    matchType: "contains",
    pattern: "TRADER JOE",
    priority: 95,
    updatedAt: seededAt,
  }),
  createRule({
    categoryId: categoryIds.dining,
    createdAt: seededAt,
    id: "rule-sweetgreen",
    isCaseSensitive: false,
    matchType: "contains",
    pattern: "SWEETGREEN",
    priority: 90,
    updatedAt: seededAt,
  }),
  createRule({
    categoryId: categoryIds.transport,
    createdAt: seededAt,
    id: "rule-uber",
    isCaseSensitive: false,
    matchType: "contains",
    pattern: "UBER",
    priority: 85,
    updatedAt: seededAt,
  }),
  createRule({
    categoryId: categoryIds.subscriptions,
    createdAt: seededAt,
    id: "rule-netflix",
    isCaseSensitive: false,
    matchType: "exact",
    pattern: "NETFLIX",
    priority: 110,
    updatedAt: seededAt,
  }),
  createRule({
    categoryId: categoryIds.amazon,
    createdAt: seededAt,
    id: "rule-amazon",
    isCaseSensitive: false,
    matchType: "contains",
    pattern: "AMAZON",
    priority: 80,
    updatedAt: seededAt,
  }),
];

const monthlySnapshots = ["2026-01", "2026-02", "2026-03"].map((monthKey) =>
  monthlySnapshotSchema.parse(
    buildMonthlySnapshot({
      categories: budgetCategories,
      generatedAt: seededAt,
      monthKey,
      transactions,
    }),
  ),
);

const appSettings = createSettings({
  activeBudgetPlanId: planId,
  createdAt: seededAt,
  currency: "USD",
  demoDataSeededAt: seededAt,
  hasCompletedOnboarding: false,
  id: settingsId,
  locale: "en-US",
  monthStartDay: 1,
  updatedAt: seededAt,
});

export type DemoSeedData = {
  appSettings: AppSettings;
  budgetCategories: BudgetCategory[];
  budgetPlan: BudgetPlan;
  merchantRules: MerchantRule[];
  monthlySnapshots: MonthlySnapshot[];
  statementImports: StatementImport[];
  transactions: Transaction[];
};

export function createDemoSeedData(): DemoSeedData {
  return {
    appSettings,
    budgetCategories,
    budgetPlan,
    merchantRules,
    monthlySnapshots,
    statementImports,
    transactions,
  };
}
